### ISSUE TITLE
More EQ band and band range for sub-band analysis?

### ISSUE THREAD

**Issue by carrus2049** [mir-aidj/transition-analysis#1] opened 2021-06-21 03:30 UTC
Grettings and great work out there!

I noticed that in the paper you set the cut-off frequencies for low & high at 180Hz and 3000Hz. As we know eq processors differs with mixers. Like another industrial standard A&H Xone 92's got a four band EQ with 2 mids by 100-250Hz and 250-2500Hz. And the one Palms Trax using, I believe a Condesa Carmen-V [(Spec Page)](https://condesaelectronics.com/shop/carmen-v/), with another cut-off frequency settings, and even with a isolator also may alter the frequency output of the mix. 

Have you considered these factors in your work? Or is there a way of analysis to fit different EQ processor? I know the difference may be subtle but I'm just curious.

**Comment by tae-jun** [comment] 2021-06-21 06:52
Thanks for your interest!

When we firstly designed the algorithm, we considered two industrial standard DJ mixers: Pioneer DJM series & Xone:9X
But for simplicity, we chose DJM because they have 3 EQ knobs whereas Xone has 4 knobs.
Xone clearly states their cut-ff frequencies, but DJM doesn't (as far as I know).
I just surfed around the internet and found a comment about the cut-off frequencies of DJM (180Hz and 3000Hz).

And yes as you said, identically EQing on spectrogram domain is quite complicated.
There is a isolator, and mid is usually bell-EQ whereas low and high have shelf-EQ
So strictly, just multiplying and adding bands on spectrogram is not equal to those EQs.
But somehow it seems to work in many cases...😅 even when the mixer model is different (I guess the differences are subtle)

And I just used 3-EQ as described in the paper for reproducibility and also because I used the Palms Trax's mix in previous work's code: https://github.com/mir-aidj/djmix-analysis
(I think it's not perfect but works if mix-to-track alignment is done correctly even though EQ model is different)

If you want to use another number of EQ bands, you can just change the number of bands, cut-off frequencies, and the number of variables for convex optimization!

**Comment by carrus2049** [comment] 2021-06-22 11:54
Good point! That I figure we can use different EQ setting and compare the reconstruction error if needed. Tho for a while I think sticking to the normal 3 bands setting is more than enough. Think I'll fiddle around abit and keep you updated if got anything good!

BTW the reconstruction result on the web demo sounds pretty promising IMO. Way to go and thanks for your time!

**Comment by tae-jun** [comment] 2021-06-23 10:31
Yeah exactly! Maybe even mixer models can be also detected by comparing the reconstruction error, though we need experiments.

Sounds great! 😄 

And please close this issue if you think this is resolved. You can open another issue whenever you have an issue you want to discuss together. Thanks!

**Closed as completed** 2021-06-23 12:26 UTC
